# Generated by Django 4.2.4 on 2024-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarksAsDone',
            fields=[
                ('work_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
            ],
        ),
    ]
